# Site settings
title: Meaty Times
description: Cooking timings and temperatures for roasting meat at home
url: https://meatytimes.markheydon.me.uk

# Language (UK English)
lang: en-GB

# Theme
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Defaults for front matter
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/calculator-results.png
